#!/usr/bin/env python3

import subprocess
import os.path
import sys

dirname = os.path.dirname(os.path.realpath(__file__))
rofi_input = os.path.join(dirname, 'unicode.tsv')

cmd = ['rofi', '-dmenu', '-i', '-no-custom', '-input', rofi_input]
result = subprocess.run(cmd, capture_output=True)
if result.returncode != 0:
    sys.exit(result.returncode)

cp = result.stdout.partition(b'\t')[0]
cp = cp[2:] # Remove "U+"
print(chr(int(cp, 16)))
